name: HothGenerator
version: 1.15
main: biz.orgin.minecraft.hothgenerator.HothGeneratorPlugin
load: STARTUP
description: Generates a really icy world.
author: orgin_org
website: http://dev.bukkit.org/server-mods/hothgenerator/
commands:
   hothreload:
      description: Reload the hoth configuration.
      usage: /hothreload
      permission: hothgenerator.hothreload
      permission-message: You don't have permission to use the hothreload command
   hothexport:
      description: Export the selected region to a schematic file.
      usage: /hothexport filename [maskid]
      permission: hothgenerator.hothexport
      permission-message: You don't have permission to use the hothexport command
   hothsavell:
      description: Save the named loot list.
      usage: /hothsavell filename
      permission: hothgenerator.hothsavell
      permission-message: You don't have permission to use the hothsavell command
   hothregion:
      description: Access the hoth region commands
      usage: /hothregion [info|flag|remove] [parameters...]
      permission: hothgenerator.hothregion
      permission-message: You don't have permission to use the hothregion command
   hothinfo:
      description: Shows some information about the plugin
      usage: /hothinfo
      permission: hothgenerator.hothinfo
      permission-message: You don't have permission to use the hothinfocommand
permissions:
    hothgenerator.*:
        description: Gives access to all hothgenerator commands
        children:
            hothgenerator.hothreload: true
            hothgenerator.hothexport: true
            hothgenerator.hothsavell: true
            hothgenerator.hothregion: true
            hothgenerator.hothinfo: true
    hothgenerator.hothreload:
        description: Reload the hoth configuration.
        default: op
    hothgenerator.hothexport:
        description: Export the selected region to a schematic file.
        default: op
    hothgenerator.hothsavell:
        description: Save the named loot list.
        default: op
    hothgenerator.hothregion:
        description: Access the hoth region commands
        default: op
    hothgenerator.hothinfo:
        description: Shows some information about the plugin
        default: true
            